name: Run tmate

on:
  workflow_dispatch:

jobs:
  tmate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install tmate
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate

      - name: Start tmate session
        run: |
          # Start tmate in the background and capture the session info
          tmate -S /tmp/tmate.sock new-session -d
          echo "tmate session started."

          # Display tmate session SSH connection string
          echo "tmate session SSH connection string:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' > connection_string.txt
          cat connection_string.txt
          
          # Optional: keep the session alive
          tmate -S /tmp/tmate.sock wait tmate-ready
          
          # Keep the job running to keep the session alive
          while true; do sleep 1; done
          
