name: Run tmate

on:
  workflow_dispatch:

jobs:
  tmate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install tmate
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate

      - name: Start tmate session
        id: start_tmate
        run: |
          # Start tmate in the background
          tmate -S /tmp/tmate.sock new-session -d
          echo "tmate session started."

          # Wait for the tmate session to be ready
          tmate -S /tmp/tmate.sock wait tmate-ready

          # Display tmate session SSH connection string
          echo "tmate session SSH connection string:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' > connection_string.txt

          # Display the connection string for logging
          cat connection_string.txt

      - name: Keep the session alive
        run: |
          # Keep the job running to keep the session alive
          echo "Keeping the tmate session alive..."
          while true; do sleep 1; done
          
